### ISSUE TITLE
caffe version

### ISSUE THREAD

**Issue by ahuamao16** [xiamenwcy/ScleraSegNet#2]
Could you please tell me what version of caffe you use？

I met this error:
[libprotobuf ERROR google/protobuf/text_format.cc:307] Error parsing text-format caffe.NetParameter: 61:12: Message type "caffe.LayerParameter" has nofield named "bn_param".
F0301 17:01:23.091033    78 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: deploy_bottom_up.pt

**Comment by xiamenwcy** [comment]
We have built an out-of-the-box Docker Caffe image (https://www.codewithgpu.com/i/xiamenwcy/IrisParseNet/casia_caffe_tifs) which is deployed on the [AutoDL](https://www.autodl.com/home) cloud server. You can use it to deploy ScleraSegNet.
